version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
before_build:
- cmd: >-
    set QTDIR='C:\Qt\5.15.0\msvc2019_64'

    set PATH=%PATH%;%QTDIR%bin;

    reg add "HKCU\Software\Digia\Versions" /v "DefaultQtVersion" /d "msvc2019_64" /f

    reg add "HKCU\Software\Digia\Versions" /v "VersionNames" /d "msvc2019_64" /f

    reg add "HKCU\Software\Digia\Versions\msvc2019_64" /v "InstallDir" /d "C:\Qt\5.15.0\msvc2019_64" /f
build:
  project: /code/Project/Project.sln
  verbosity: minimal
artifacts:
- path: code/bin
  name: project$(appveyor_build_version)
deploy:
- provider: GitHub
  auth_token:
    secure: IpiLn/lcCCDsGWAA7aFif66thLTnfEO3L5JqZjaIu2SNaMIuj1O9f/zgecJH7VK2
  on:
    APPVEYOR_REPO_TAG: true