version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
platform: x64
before_build:
- cmd: >-
    reg add "HKCU\Software\Digia\Versions" /v "DefaultQtVersion" /d "msvc2019_64" /f

    reg add "HKCU\Software\Digia\Versions" /v "VersionNames" /d "msvc2019_64" /f

    reg add "HKCU\Software\Digia\Versions\msvc2019_64" /v "InstallDir" /d "C:\Qt\5.15.0\msvc2019_64" /f
build:
  project: /code/Project/Project.sln
  verbosity: minimal
after_build:
- cmd: if "%APPVEYOR_REPO_TAG%"=="true" C:\Qt\5.15.0\msvc2019_64\bin\windeployqt C:\projects\cpp-project-2020\code\bin\Project.exe
artifacts:
- path: code/bin
  name: Project$(appveyor_build_version)
deploy:
- provider: GitHub
  auth_token:
    secure: IpiLn/lcCCDsGWAA7aFif66thLTnfEO3L5JqZjaIu2SNaMIuj1O9f/zgecJH7VK2
  artifact: Project$(appveyor_build_version)
  draft: true
